server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/logistics_db
    username: root
    password: 你的密碼
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
